[package]
name = "bento_utils"
version = "0.1.0"
authors = ["Danyang Zhuo <danyangz@cs.washington.edu>",
           "Kaiyuan Zhang <kaiyuanz@cs.washington.edu>",
           "Samantha Miller <sm237@cs.washington.edu>"]

[dependencies]
fuse = "0.3.1"
libc = "0.2.76"
serde = "1.0.115"
time = "0.1"
