[package]
name = "datablock_test"
version = "0.1.0"
authors = ["Kaiyuan Zhang <kaiyuanz@cs.washington.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datablock = { path = "../datablock"}